# Deploy PADRAO do worker pesado: wrangler empacota src/heavy.ts com esbuild interno
name = "rolldown-heavy"
main = "src/heavy.ts"
compatibility_date = "2025-08-13"
minify = true
account_id = "78fedbeba68de80a823e65652da5f2c5"

[observability]
enabled = true

[vars]
GREETING = "Hello"
APP_NAME = "rolldown-heavy"
